development:
  cert: '/config/push_certs/push-development-cert.pem'
  url: 'gateway.sandbox.push.apple.com'

production:
  cert: '/config/push_certs/push-production-cert.pem'
  url: 'gateway.push.apple.com'
